/// A range of cells `[lo, hi)` per axis of a crystal (§3.3.2).
public struct CellBox: Sendable, Hashable {
    public var lo: SIMD3<UInt64>
    public var hi: SIMD3<UInt64>

    public init(lo: SIMD3<UInt64>, hi: SIMD3<UInt64>) {
        self.lo = lo
        self.hi = hi
    }

    public func extent(_ a: Int) -> UInt64 { hi[a] - lo[a] }
}

/// Atoms generated by a crystal, before the one Q16 → f32 rounding (§1.4).
struct CrystalAtoms {
    var atomicNumbers: [UInt8] = []
    /// Q16 positions: relative to the box corner for a box, to the origin for a capped crystal.
    var q16: [SIMD3<Int64>] = []
    /// Global quarter-grid points (boxes only), for owner cells.
    var grid: [SIMD3<Int64>] = []

    var leaf: LeafNode {
        LeafNode(atomicNumbers: atomicNumbers, positions: q16.map { CrystalMath.f32($0) })
    }
}

/// `lupi.gen.crystal@1` (§3.3).
public enum CrystalMath {
    /// One site of the cubic cell, in quarter steps, with its sublattice.
    struct Site {
        var s: SIMD3<Int64>
        var sublattice: Int
    }

    static func sites(_ structure: CrystalNode.Structure) -> [Site] {
        func t(_ x: Int64, _ y: Int64, _ z: Int64, _ l: Int) -> Site { Site(s: SIMD3(x, y, z), sublattice: l) }
        switch structure {
        case .sc: return [t(0, 0, 0, 0)]
        case .bcc: return [t(0, 0, 0, 0), t(2, 2, 2, 1)]
        case .fcc: return [t(0, 0, 0, 0), t(0, 2, 2, 0), t(2, 0, 2, 0), t(2, 2, 0, 0)]
        case .diamond:
            return [
                t(0, 0, 0, 0), t(0, 2, 2, 0), t(2, 0, 2, 0), t(2, 2, 0, 0),
                t(1, 1, 1, 1), t(1, 3, 3, 1), t(3, 1, 3, 1), t(3, 3, 1, 1),
            ]
        case .rocksalt:
            return [
                t(0, 0, 0, 0), t(0, 2, 2, 0), t(2, 0, 2, 0), t(2, 2, 0, 0),
                t(2, 0, 0, 1), t(0, 2, 0, 1), t(0, 0, 2, 1), t(2, 2, 2, 1),
            ]
        }
    }

    static func species(_ c: CrystalNode, _ sublattice: Int) -> UInt8 {
        sublattice == 0 || c.speciesB == 0 ? c.speciesA : c.speciesB
    }

    /// The Q16 → f32 rounding of §1.4: `Float(Double(q) / 65536)`.
    @inline(__always) public static func f32(_ q: Int64) -> Float { Float(Double(q) / 65536.0) }

    static func f32(_ q: SIMD3<Int64>) -> SIMD3<Float> { SIMD3(f32(q.x), f32(q.y), f32(q.z)) }

    public static func rootBox(_ c: CrystalNode) -> CellBox { CellBox(lo: .zero, hi: c.cells) }

    /// Per-site extents of a box: `hi − lo`, plus the closed far-face layer where the site lies on it.
    private static func extents(_ c: CrystalNode, _ box: CellBox, _ site: Site) -> [UInt64] {
        (0..<3).map { a in
            var e = box.hi[a] - box.lo[a]
            if c.termination == .closed && site.s[a] == 0 && box.hi[a] == c.cells[a] { e += 1 }
            return e
        }
    }

    /// The atom count of an open or closed box, closed-form (§3.3.2).
    public static func boxCount(_ c: CrystalNode, _ box: CellBox) -> BigUInt {
        var total = BigUInt()
        for site in sites(c.structure) {
            let e = extents(c, box, site)
            total += BigUInt(e[0]) * BigUInt(e[1]) * BigUInt(e[2])
        }
        return total
    }

    /// Per-species counts of an open or closed box, closed-form.
    public static func speciesCounts(_ c: CrystalNode, _ box: CellBox) -> [UInt8: BigUInt] { boxComposition(c, box) }

    static func boxComposition(_ c: CrystalNode, _ box: CellBox) -> [UInt8: BigUInt] {
        var out: [UInt8: BigUInt] = [:]
        for site in sites(c.structure) {
            let e = extents(c, box, site)
            out[species(c, site.sublattice), default: BigUInt()] += BigUInt(e[0]) * BigUInt(e[1]) * BigUInt(e[2])
        }
        return out
    }

    /// The atoms of a box in materialization order (§3.3.2). The caller keeps boxes at ≤ 4,096 atoms.
    static func materializeBox(_ c: CrystalNode, _ box: CellBox) -> CrystalAtoms {
        let n = c.cells
        let quarter = Int64(c.quarterQ16)
        let ext = (0..<3).map { a in c.termination == .closed && box.hi[a] == n[a] ? UInt64(1) : 0 }
        let list = sites(c.structure)
        let corner = SIMD3(Int64(box.lo.x) * 4, Int64(box.lo.y) * 4, Int64(box.lo.z) * 4)
        let limit = SIMD3(Int64(n.x) * 4, Int64(n.y) * 4, Int64(n.z) * 4)
        var out = CrystalAtoms()
        for k in box.lo.z..<(box.hi.z + ext[2]) {
            for j in box.lo.y..<(box.hi.y + ext[1]) {
                for i in box.lo.x..<(box.hi.x + ext[0]) {
                    let cell = SIMD3(Int64(i) * 4, Int64(j) * 4, Int64(k) * 4)
                    for site in list {
                        let g = Int3.add(cell, site.s)
                        // Only face sites in the closed crystal's extra layer.
                        if g.x > limit.x || g.y > limit.y || g.z > limit.z { continue }
                        out.atomicNumbers.append(species(c, site.sublattice))
                        out.grid.append(g)
                        out.q16.append(Int3.scale(Int3.sub(g, corner), quarter))
                    }
                }
            }
        }
        return out
    }

    /// The atoms of an open or closed box without removals, in materialization order, with each
    /// atom's owner cell. The caller keeps boxes at ≤ 4,096 atoms.
    public static func atoms(_ c: CrystalNode, _ box: CellBox) -> (leaf: LeafNode, cells: [SIMD3<UInt64>]) {
        let a = materializeBox(c, box)
        return (a.leaf, a.grid.map { ownerCell(c, $0) })
    }

    /// The owner cell of a grid point: `min(⌊g / 4⌋, n − 1)` per axis (§3.3.2).
    public static func ownerCell(_ c: CrystalNode, _ g: SIMD3<Int64>) -> SIMD3<UInt64> {
        SIMD3(
            min(UInt64(g.x / 4), c.cells.x - 1),
            min(UInt64(g.y / 4), c.cells.y - 1),
            min(UInt64(g.z / 4), c.cells.z - 1)
        )
    }

    static func contains(_ box: CellBox, _ cell: SIMD3<UInt64>) -> Bool {
        (0..<3).allSatisfy { cell[$0] >= box.lo[$0] && cell[$0] < box.hi[$0] }
    }

    // MARK: Octree (§3.3.3)

    /// The children of a box in increasing octant order; empty for one cell.
    public static func octreeChildren(_ box: CellBox) -> [(octant: UInt8, box: CellBox)] {
        var split = [Bool](repeating: false, count: 3)
        var mid = SIMD3<UInt64>.zero
        for a in 0..<3 {
            let e = box.hi[a] - box.lo[a]
            split[a] = e >= 2
            mid[a] = box.lo[a] + (e + 1) / 2
        }
        guard split.contains(true) else { return [] }
        var out: [(UInt8, CellBox)] = []
        for o in 0..<8 {
            var lo = box.lo, hi = box.hi
            var exists = true
            for a in 0..<3 {
                let upper = (o >> a) & 1 == 1
                if upper && !split[a] { exists = false; break }
                guard split[a] else { continue }
                if upper { lo[a] = mid[a] } else { hi[a] = mid[a] }
            }
            if exists { out.append((UInt8(o), CellBox(lo: lo, hi: hi))) }
        }
        return out
    }

    public static func octreeChild(_ box: CellBox, _ octant: UInt8) throws -> CellBox {
        guard let child = octreeChildren(box).first(where: { $0.octant == octant }) else {
            throw fail(.path, "octant \(octant) does not exist")
        }
        return child.box
    }

    // MARK: Capped diamondoids (§3.3.4)

    static let diamondDirections: [[SIMD3<Int64>]] = [
        [SIMD3(1, 1, 1), SIMD3(1, -1, -1), SIMD3(-1, 1, -1), SIMD3(-1, -1, 1)],
        [SIMD3(-1, -1, -1), SIMD3(-1, 1, 1), SIMD3(1, -1, 1), SIMD3(1, 1, -1)],
    ]

    static func isDiamondSite(_ p: SIMD3<Int64>) -> Bool {
        let par = p.x & 1
        guard p.y & 1 == par, p.z & 1 == par else { return false }
        let q = par == 1 ? Int3.sub(p, SIMD3(1, 1, 1)) : p
        return ((q.x + q.y + q.z) % 4 + 4) % 4 == 0
    }

    /// The atoms of a capped crystal, Q16 from the crystal origin.
    static func materializeCapped(_ c: CrystalNode) throws -> CrystalAtoms {
        let m = Int64(c.cells.x)
        let centre = 2 * m, radius = 2 * m + 1
        var sites: [SIMD3<Int64>] = []
        var index: [SIMD3<Int64>: Int] = [:]
        for z in (centre - radius)...(centre + radius) {
            for y in (centre - radius)...(centre + radius) {
                for x in (centre - radius)...(centre + radius) {
                    let p = SIMD3(x, y, z)
                    if abs(x - centre) + abs(y - centre) + abs(z - centre) > radius { continue }
                    if isDiamondSite(p) {
                        index[p] = sites.count
                        sites.append(p)
                    }
                }
            }
        }
        func sublattice(_ p: SIMD3<Int64>) -> Int { p.x & 1 == 1 ? 1 : 0 }
        let kept = sites.map { p in
            diamondDirections[sublattice(p)].filter { index[Int3.add(p, $0)] != nil }.count >= 2
        }
        let quarter = Int64(c.quarterQ16), cap = Int64(c.capOffsetQ16)
        var out = CrystalAtoms()
        for (i, p) in sites.enumerated() where kept[i] {
            let l = sublattice(p)
            out.atomicNumbers.append(species(c, l))
            out.q16.append(Int3.scale(p, quarter))
            for d in diamondDirections[l] {
                if let ni = index[Int3.add(p, d)], kept[ni] { continue }
                out.atomicNumbers.append(c.capZ)
                out.q16.append(Int3.add(Int3.scale(p, quarter), Int3.scale(d, cap)))
            }
        }
        if out.atomicNumbers.count > RecordLimits.maxAtoms { throw fail(.limit, "capped crystal beyond 4,096 atoms") }
        return out
    }
}

/// Checked integer vector arithmetic: an overflow is a bug, never a wrap (§1.10).
enum Int3 {
    @inline(__always) static func add(_ a: SIMD3<Int64>, _ b: SIMD3<Int64>) -> SIMD3<Int64> {
        SIMD3(a.x + b.x, a.y + b.y, a.z + b.z)
    }

    @inline(__always) static func sub(_ a: SIMD3<Int64>, _ b: SIMD3<Int64>) -> SIMD3<Int64> {
        SIMD3(a.x - b.x, a.y - b.y, a.z - b.z)
    }

    @inline(__always) static func scale(_ a: SIMD3<Int64>, _ k: Int64) -> SIMD3<Int64> {
        SIMD3(a.x * k, a.y * k, a.z * k)
    }
}
