// Generated by tools/build-omol25-featured.mjs from tools/omol25-featured.picks.json. Do not edit.
// Landing-safe: imports nothing. Empty until the featured build has run (it needs @atlas/core/bonds).

export interface OmolPick {
  id: string;
  title: string;
  formula: string;
  atoms: number;
  elements: string[];
  shelf: string;
  home: boolean;
  domainLabel: string;
  charge: number;
  spinMultiplicity: number;
  file: string;
  ink: string;
}

export const OMOL_PICKS: readonly OmolPick[] = [];
