// Generated by tools/build-omol25-featured.mjs from tools/omol25-featured.picks.json. Do not edit.
// Landing-safe: imports nothing. One compact row per pick keeps the landing chunk under 1 KB gzip.

export interface OmolPick {
  id: string;
  title: string;
  formula: string;
  atoms: number;
  elements: string[];
  shelf: string;
  home: boolean;
  domainLabel: string;
  charge: number;
  spinMultiplicity: number;
  file: string;
  ink: string;
}

type Row = readonly [row: number, title: string | null, formula: string, atoms: number, shelf: string, home: 0 | 1, domainLabel: string, charge: number, spinMultiplicity: number];

const ROWS: readonly Row[] = [
];

export const OMOL_PICKS: readonly OmolPick[] = ROWS.map(([row, title, formula, atoms, shelf, home, domainLabel, charge, spinMultiplicity]) => ({
  id: `omol25_nv_${row}`,
  title: title ?? formula,
  formula,
  atoms,
  elements: formula.match(/[A-Z][a-z]?/g) ?? [],
  shelf,
  home: home === 1,
  domainLabel,
  charge,
  spinMultiplicity,
  file: `/datasets/omol25/featured/omol25_nv_${row}.xyz`,
  ink: `/og/omol25/omol25_nv_${row}-ink.svg`,
}));
