// LupiScale v1, the TypeScript reference (docs/ar/scale-spec.md §11.2). It
// writes the golden fixtures the Swift implementation (apps/apple/LupiScale)
// reads, so every [B] rule here is byte-exact.

export {
  ASCII,
  base64url,
  bigUIntBytes,
  bigUIntFromBytes,
  bitLength,
  bytesEqual,
  compareBytes,
  concatBytes,
  fromBase64url,
  fromHex,
  Reader,
  ScaleError,
  toHex,
  Writer,
  type ScaleErrorCode,
} from './bytes';
export { crc32, domain, leU64, mix64, sha256, Sha256, SplitMix64 } from './hash';
export {
  canonicalQuaternion,
  decodeRecord,
  encodeRecord,
  IDENTITY_ROTATION,
  KIND,
  nodeId,
  periodDeterminant,
  periodsSlenderOk,
  quaternionCanonical,
  quaternionNormOk,
  STRUCTURE,
  TERMINATION,
  type CrystalNode,
  type DecodedRecord,
  type EditNode,
  type GroupChild,
  type GroupNode,
  type LeafNode,
  type LeafNode as Leaf,
  type Node,
  type NodeID,
  type Structure,
  type Substitution,
  type TowerNode,
  type Vec3n,
} from './records';
export {
  boxChild,
  boxChildren,
  boxComposition,
  boxCount,
  leafFromQ16,
  materializeBox,
  materializeCapped,
  q16ToF32,
  rootBox,
  SITES,
  type Box,
  type Q16Atoms,
} from './crystal';
export {
  copyKey,
  fullTowerStep,
  levelsAlong,
  levelsAlongSpan,
  periodsAngstrom,
  substitute,
  towerAxis,
  unitExponent,
} from './tower';
export { editFits, editRecordLength, removeFrom } from './edit';
export {
  canonicalPath,
  comparePaths,
  composeRanges,
  decodePath,
  encodePath,
  indicesToRanges,
  isCanonical,
  pathContains,
  rangesIndices,
  readPath,
  runsLength,
  stepBytes,
  TAG,
  type AtomRange,
  type AxisRuns,
  type DigitRun,
  type Step,
} from './paths';
export {
  ChainStore,
  MemoryStore,
  Resolver,
  TrackingStore,
  type NodeStore,
  type Removal,
  type View,
  type ViewType,
} from './resolve';
export {
  addMagnitude,
  compareMagnitude,
  displayRuns,
  fitsPlain,
  formatMagnitude,
  formatMagnitudeDetailed,
  lnBig,
  lnlnMagnitude,
  lnMagnitude,
  log10Magnitude,
  magnitude,
  Magnitude,
  magnitudeEquals,
  magnitudeKey,
  mulSmallMagnitude,
  rootBase,
  subMagnitude,
  toPlain,
  towerMagnitude,
  withDisplayBase,
} from './magnitude';
export {
  compositionCount,
  countsOf,
  elementSymbol,
  formulaText,
  hillFormula,
  massMicroDa,
  MICRO_DA_V1,
  microDaltons,
  microDaltonsFromLiteral,
  type Composition,
} from './composition';
export { Pack, packContentId, packFileHash, readPack, writePack, type PackRoot, type PackSection } from './pack';
export {
  decodeRef,
  encodeRef,
  refFromText,
  refKey,
  refText,
  resolveRef,
  writeRef,
  type DecodedRef,
  type ScaleRef,
} from './ref';
export { bakePartition, mortonKeyBig, partitionOrder, type PartitionResult } from './partition';
