// Generated by tools/build-hero-data.mjs from apps/web/public/gallery/curated/c60_buckyball.xyz. Do not edit.
// Regenerate: node tools/build-hero-data.mjs
//
// C60 centred on its bounds centre (the viewer's fit target), Å. The
// turntable at 29.75° passes 8 faces within 12° (4 hexagons, 4 pentagons;
// largest gap 70.0°). Angles are radians: camera azimuth about world +Y
// and elevation, viewDir = (cos el·sin az, sin el, cos el·cos az).

export interface C60HeroDetent {
  azimuth: number;
  /** The face's own elevation: a detent is exactly face-on. */
  elevation: number;
  label: 'Hexagon' | 'Pentagon';
}

export interface C60HeroData {
  /** x, y, z per atom (Å, bounds-centred). */
  positions: number[];
  /** Atom index pairs. */
  bonds: number[];
  /** Largest atom distance from the centre (Å). */
  radius: number;
  /** The turntable circle's elevation (rad); each detent carries its face's own. */
  elevation: number;
  /** Face-on azimuths along the turntable, ascending in (−π, π]. */
  detents: C60HeroDetent[];
  /** The hexagon detent nearest 30° (its elevation is openingElevation): the pose the page opens on. */
  openingAzimuth: number;
  openingElevation: number;
}

export const C60_HERO: C60HeroData = {
  positions: [
    2.2102, 0.5866, 2.6669, 3.1076, 0.1577, 1.6299, 1.3284, -0.3159, 3.2362, 3.0908, -1.1585, 1.2013,
    3.1879, -1.4575, -0.1998, 3.2214, 1.2231, 0.6739, 3.3161, 0.9351, -0.6766, 3.2985, -0.4301, -1.1205,
    -0.4481, 1.3591, 3.208, 0.4672, 2.295, 2.6174, -0.0257, 0.0764, 3.5085, 1.7728, 1.9176, 2.3529,
    2.3954, 2.3095, 1.1189, -0.261, 3.0821, 1.6622, 0.3407, 3.4592, 0.4745, 1.6951, 3.0692, 0.1976,
    -2.1259, -0.8459, 2.67, -2.5621, 0.4855, 2.3531, -0.8782, -1.0462, 3.2366, -1.7415, 1.568, 2.6196,
    -1.6263, 2.6357, 1.6641, -3.2985, 0.4302, 1.1203, -3.188, 1.4574, 0.1995, -2.3361, 2.5813, 0.476,
    -0.5005, -2.9798, 1.7939, -1.7945, -2.7729, 1.2047, -0.0514, -2.1329, 2.7938, -2.5892, -1.7226, 1.6329,
    -3.3161, -0.9351, 0.6764, -1.6952, -3.0693, -0.1977, -2.3955, -2.3097, -1.1191, -3.2214, -1.2232, -0.674,
    2.1758, -2.0947, 1.7922, 1.7118, -2.975, 0.7556, 1.313, -1.683, 2.7943, 0.3959, -3.4052, 0.7557,
    -0.3408, -3.4592, -0.4747, 2.336, -2.5815, -0.4762, 1.6264, -2.6358, -1.6643, 0.2611, -3.0822, -1.6624,
    -2.2101, -0.5869, -2.6671, -1.7727, -1.9179, -2.3531, -0.4671, -2.2951, -2.6176, -1.3284, 0.3157, -3.2363,
    -2.176, 2.0945, -1.7924, -3.091, 1.1583, -1.2017, -3.1076, -0.1579, -1.6303, -1.3132, 1.6828, -2.7945,
    0.5003, 2.9799, -1.7941, -0.3961, 3.4053, -0.7558, -1.7121, 2.9749, -0.7559, 0.0513, 2.1329, -2.7938,
    2.1258, 0.8461, -2.6701, 2.5892, 1.7227, -1.633, 1.7943, 2.773, -1.2049, 0.8781, 1.0463, -3.2366,
    0.4482, -1.3591, -3.2081, 1.7417, -1.568, -2.6199, 2.5621, -0.4854, -2.3533, 0.0258, -0.0764, -3.5085,
  ],
  bonds: [
    0, 1, 0, 2, 0, 11, 1, 3, 1, 5, 2, 10, 2, 34, 3, 4, 3, 32, 4, 7,
    4, 37, 5, 6, 5, 12, 6, 7, 6, 53, 7, 58, 8, 9, 8, 10, 8, 19, 9, 11,
    9, 13, 10, 18, 11, 12, 12, 15, 13, 14, 13, 20, 14, 15, 14, 49, 15, 54, 16, 17,
    16, 18, 16, 27, 17, 19, 17, 21, 18, 26, 19, 20, 20, 23, 21, 22, 21, 28, 22, 23,
    22, 45, 23, 50, 24, 25, 24, 26, 24, 35, 25, 27, 25, 29, 26, 34, 27, 28, 28, 31,
    29, 30, 29, 36, 30, 31, 30, 41, 31, 46, 32, 33, 32, 34, 33, 35, 33, 37, 35, 36,
    36, 39, 37, 38, 38, 39, 38, 57, 39, 42, 40, 41, 40, 43, 40, 46, 41, 42, 42, 56,
    43, 47, 43, 59, 44, 45, 44, 47, 44, 50, 45, 46, 47, 51, 48, 49, 48, 51, 48, 54,
    49, 50, 51, 55, 52, 53, 52, 55, 52, 58, 53, 54, 55, 59, 56, 57, 56, 59, 57, 58,
  ],
  radius: 3.5164,
  elevation: 0.519235,
  detents: [
    { azimuth: -3.0337, elevation: 0.314904, label: 'Pentagon' },
    { azimuth: -1.811908, elevation: 0.673127, label: 'Pentagon' },
    { azimuth: -1.051513, elevation: 0.494316, label: 'Hexagon' },
    { azimuth: -0.297553, elevation: 0.726434, label: 'Pentagon' },
    { azimuth: 0.292904, elevation: 0.311659, label: 'Hexagon' },
    { azimuth: 0.984388, elevation: 0.385698, label: 'Pentagon' },
    { azimuth: 1.67199, elevation: 0.673196, label: 'Hexagon' },
    { azimuth: 2.604526, elevation: 0.637829, label: 'Hexagon' },
  ],
  openingAzimuth: 0.292904,
  openingElevation: 0.311659,
};
