#!/usr/bin/env -S npx tsx
/**
 * gen-elements.mts — writes LupiKit's element table from the web's.
 *
 * Reads packages/core/src/elements.ts (symbol, name, mass, Cordero covalent
 * radius, display radius, CPK colour, category, electronegativity) so the app
 * and the viewer can never disagree on a colour or a bond cutoff, and adds a
 * van der Waals radius, which the web table does not carry.
 *
 *   pnpm exec tsx tools/apple/gen-elements.mts          # write
 *   pnpm exec tsx tools/apple/gen-elements.mts --check  # exit 1 when stale
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ELEMENT_DATA, type ElementCategory } from '../../packages/core/src/elements';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const OUT = path.join(ROOT, 'apps/apple/LupiKit/Sources/LupiChem/Elements.generated.swift');

/**
 * Van der Waals radii in pm: the "AtomicRadius" column of the PubChem
 * Periodic Table (https://pubchem.ncbi.nlm.nih.gov/rest/pug/periodictable/JSON,
 * fetched 2026-10-04), which PubChem documents as the van der Waals radius.
 * It has no value from Fm (Z 100) on; those get VDW_FALLBACK_PM.
 */
const VDW_RADII_PM: Readonly<Record<number, number>> = {
  1: 120, 2: 140, 3: 182, 4: 153, 5: 192, 6: 170, 7: 155, 8: 152, 9: 135, 10: 154,
  11: 227, 12: 173, 13: 184, 14: 210, 15: 180, 16: 180, 17: 175, 18: 188, 19: 275, 20: 231,
  21: 211, 22: 187, 23: 179, 24: 189, 25: 197, 26: 194, 27: 192, 28: 163, 29: 140, 30: 139,
  31: 187, 32: 211, 33: 185, 34: 190, 35: 183, 36: 202, 37: 303, 38: 249, 39: 219, 40: 186,
  41: 207, 42: 209, 43: 209, 44: 207, 45: 195, 46: 202, 47: 172, 48: 158, 49: 193, 50: 217,
  51: 206, 52: 206, 53: 198, 54: 216, 55: 343, 56: 268, 57: 240, 58: 235, 59: 239, 60: 229,
  61: 236, 62: 229, 63: 233, 64: 237, 65: 221, 66: 229, 67: 216, 68: 235, 69: 227, 70: 242,
  71: 221, 72: 212, 73: 217, 74: 210, 75: 217, 76: 216, 77: 202, 78: 209, 79: 166, 80: 209,
  81: 196, 82: 202, 83: 207, 84: 197, 85: 202, 86: 220, 87: 348, 88: 283, 89: 260, 90: 237,
  91: 243, 92: 240, 93: 221, 94: 243, 95: 244, 96: 245, 97: 244, 98: 245, 99: 245,
};
/** Lupi choice for Z ≥ 100, which have no measured radius: about the late actinides'. */
const VDW_FALLBACK_PM = 245;

const CATEGORY_CASE: Readonly<Record<ElementCategory, string>> = {
  'alkali-metal': 'alkaliMetal',
  'alkaline-earth': 'alkalineEarth',
  'transition-metal': 'transitionMetal',
  'post-transition-metal': 'postTransitionMetal',
  metalloid: 'metalloid',
  nonmetal: 'nonmetal',
  halogen: 'halogen',
  'noble-gas': 'nobleGas',
  lanthanide: 'lanthanide',
  actinide: 'actinide',
  unknown: 'unknown',
};

/** JS's shortest round-trip decimal; Swift parses it back to the same double. */
const num = (value: number): string => {
  const text = String(value);
  return /[.eE]/.test(text) ? text : `${text}.0`;
};
const str = (value: string): string => JSON.stringify(value);

function colorLiteral(hex: string): string {
  if (!/^#[0-9a-f]{6}$/i.test(hex)) throw new Error(`element colour ${hex} is not #rrggbb`);
  return `0x${hex.slice(1).toUpperCase()}`;
}

export function renderElementsSwift(): string {
  const zs = Object.keys(ELEMENT_DATA).map(Number).sort((a, b) => a - b);
  zs.forEach((z, index) => {
    if (z !== index + 1) throw new Error(`element table has a gap at Z ${index + 1}`);
  });
  const rows = zs.map((z) => {
    const e = ELEMENT_DATA[z];
    const vdw = (VDW_RADII_PM[z] ?? VDW_FALLBACK_PM) / 100;
    const en = e.electronegativity === null ? 'nil' : num(e.electronegativity);
    return `        Element(z: ${z}, symbol: ${str(e.symbol)}, name: ${str(e.name)}, mass: ${num(e.mass)}, `
      + `covalentRadius: ${num(e.radius)}, vdwRadius: ${num(vdw)}, displayRadius: ${num(e.displayRadius)}, `
      + `cpk: CPKColor(hex: ${colorLiteral(e.color)}), category: .${CATEGORY_CASE[e.category]}, electronegativity: ${en}),`;
  });
  return [
    '// Generated by tools/apple/gen-elements.mts from packages/core/src/elements.ts. Do not edit.',
    '// Covalent radii: Cordero 2008 (Pyykkö 2009 where Cordero has none), as the web table.',
    '// Van der Waals radii: PubChem Periodic Table (AtomicRadius, pm); Z >= 100 use 2.45 Å.',
    '',
    'extension Element {',
    '    /// Z 1...118 in order: `table[z - 1]`.',
    '    static let table: [Element] = [',
    ...rows,
    '    ]',
    '}',
    '',
  ].join('\n');
}

const isMain = process.argv[1] !== undefined && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const text = renderElementsSwift();
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
    if (current !== text) {
      console.error(`${path.relative(ROOT, OUT)} is stale: run pnpm exec tsx tools/apple/gen-elements.mts`);
      process.exit(1);
    }
    console.log(`${path.relative(ROOT, OUT)} is up to date`);
  } else {
    fs.writeFileSync(OUT, text);
    console.log(`wrote ${path.relative(ROOT, OUT)} (${Object.keys(ELEMENT_DATA).length} elements)`);
  }
}
